# -*- coding: utf-8 -*-
"""datasetDownload.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yWZZg7KaevI7X_NwlT3_6knFi_9vDzX
"""

def colabDownloadKaggleDataSet(dataSetName, \
                               kaggle_username='lin3372', kaggle_key='6864869e0f26f7cde2c8a93ca73b224c',\
                               gdrive_mnt_pt='/gdrive/',\
                               kaggle_dataset_colab_dir='/content/dataSet/', \
                               kaggle_json_file_src='/gdrive/MyDrive/00_AI.Garden/01_Github/util/kaggle/kaggle.json',\
                               kaggle_json_file_working_dir='/content/dataSet/kaggle.json'):
  import sys  
  import os
  import shutil
  import json
  import subprocess
  
  #!pip install kaggle
  # implement pip as a subprocess:
  subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'kaggle'])

  IN_COLAB = 'google.colab' in sys.modules 

  if not IN_COLAB:
    print('Not in Colab, exit!')
    return

  #token = {"username":"lin3372","key":"6864869e0f26f7cde2c8a93ca73b224c"}
  token = {"username":kaggle_username,"key":kaggle_key}
  
  #GDRIVE_MOUNT_PT='/gdrive/'
  #KAGGLE_DATATSET_COLAB_DIR='/content/dataSet/'
  #KAGGLE_JSON_FILE_SRC=GDRIVE_MOUNT_PT + 'MyDrive/00_AI.Garden/01_Github/util/kaggle/kaggle.json'
  #KAGGLE_JSON_FILE_WORKING_DIR = KAGGLE_DATATSET_COLAB_DIR + 'kaggle.json'

  GDRIVE_MOUNT_PT = gdrive_mnt_pt
  KAGGLE_DATATSET_COLAB_DIR = kaggle_dataset_colab_dir
  KAGGLE_JSON_FILE_SRC = kaggle_json_file_src
  KAGGLE_JSON_FILE_WORKING_DIR = kaggle_json_file_working_dir

  #os.environ['KAGGLE_USERNAME']='lin3372'
  #os.environ['KAGGLE_KEY']='6864869e0f26f7cde2c8a93ca73b224c'
  os.environ['KAGGLE_USERNAME'] = kaggle_username
  os.environ['KAGGLE_KEY'] = kaggle_key  
  os.environ['KAGGLE_CONFIG_DIR'] = KAGGLE_DATATSET_COLAB_DIR  

  from google.colab import drive
  drive.mount(GDRIVE_MOUNT_PT) 

  from kaggle.api.kaggle_api_extended import KaggleApi
  api = KaggleApi()
  api.authenticate()
  
  os.makedirs(KAGGLE_DATATSET_COLAB_DIR, exist_ok=True)
  print(f'Creating dir @ {KAGGLE_DATATSET_COLAB_DIR}')
  shutil.copy2(KAGGLE_JSON_FILE_SRC, KAGGLE_DATATSET_COLAB_DIR)
  print(f'Copying kaggle.json from {KAGGLE_JSON_FILE_SRC} to {KAGGLE_DATATSET_COLAB_DIR}')
  os.chmod(KAGGLE_JSON_FILE_WORKING_DIR, 0o600)

  CURDIR=os.getcwd()
  os.chdir(KAGGLE_DATATSET_COLAB_DIR)

  with open(KAGGLE_JSON_FILE_WORKING_DIR, 'w') as file:
    json.dump(token, file)

  #!kaggle config set -n path -v{KAGGLE_DATATSET_COLAB_DIR} 

  print(f'dataSet = {dataSetName}')

  #!kaggle competitions download -c $dataSetName -p ./
  api.dataset_download_files(f'{dataSetName}', path=KAGGLE_DATATSET_COLAB_DIR)  
  #!kaggle datasets download -d $dataSetName  #jessicali9530/celeba-dataset

  os.chdir(CURDIR)

  return KAGGLE_DATATSET_COLAB_DIR