# -*- coding: utf-8 -*-
"""iLKaggleFn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_8mExsejHMsfAY6gNAf21_WiIqoy4jZ
"""

# Commented out IPython magic to ensure Python compatibility.
def colabKaggleDataDownload(dataSetName, pathJson='./kaggle/kaggle.json'):
  import os
  import os.path
  from os import path
  import shutil
  from kaggle.api.kaggle_api_extended import KaggleApi
  
  IVAN_GDRIVE_AI_GITHUB_DIR = '/content/gdrive/My Drive/00_AI.Garden/01_Github/'
  IVAN_GDRIVE_KAGGLE_DIR = IVAN_GDRIVE_AI_GITHUB_DIR + '/util/kaggle/'
  
  print('colabKaggleDataDownload - Downloading Kaggle Dataset: ', dataSetName)
  print('Gdrive json file @ ', IVAN_GDRIVE_KAGGLE_DIR)
  print(os.listdir(IVAN_GDRIVE_KAGGLE_DIR))

  !pip install kaggle --quiet

  if not os.path.isdir("./iLUtil"):
    print("\tErr: iLUtil not exist")
    print("\tErr: Pls clone from github lin3372/iLUtil.git")
    print("\t\t!git clone https://github.com/lin3372/iLUtil.git")


  # sanity check -- iLUtil (Ivan's utility functions)
  print("kaggleDataSetDownload: ", "Current Directory = ", os.getcwd())
  if not os.path.isdir("./iLUtil"):
    print("\tErr: iLUtil not exist")
    print("\tErr: Pls clone from github lin3372/iLUtil.git")
    print("\t\t!git clone https://github.com/lin3372/iLUtil.git")

  # sanity check -- remove old /root/.kaggle if it still exist, and copy the new kaggle.json
  if path.exists("/root/.kaggle/"):
    if os.path.isfile("/root/.kaggle"):
      print("\tremoving file /root/.kaggle/")
      os.rm("/root/.kaggle")
    elif os.path.isdir("/root/.kaggle"):
      print("\tremoving dir /root/.kaggle/")
      shutil.rmtree("/root/.kaggle", ignore_errors=True)   
  print("\tcreating /root/.kaggle/")
  !mkdir /root/.kaggle

  # sanity check -- remove old ./dataSetKaggle if it still exist
  if path.exists("./dataSetKaggle"):
    if os.path.isfile("./dataSetKaggle"):
      print("\tremoving file ./dataSetKaggle/")
      os.rm("./dataSetKaggle")
    elif os.path.isdir("./dataSetKaggle/"):
      print("\tremoving dir ./dataSetKaggle/")
      shutil.rmtree("./dataSetKaggle/", ignore_errors=True)   
      #os.rmdir("./dataSetKaggle/")    
  print("\tcreating ./dataSetKaggle/")
  !mkdir ./dataSetKaggle

  print("\tcopying kaggle.json from ./iLUtil/kaggle/kaggle.json to /root/.kaggle/")
  !cp ../iLUtil/kaggle/kaggle.json /root/.kaggle/
  !chmod 600 /root/.kaggle/kaggle.json

  api = KaggleApi()
  api.authenticate()
  api.competition_download_files(dataSetName)  

  !ls -l ./dataSetKaggle/
  print("\tFinished Downloading Kaggle DataSet - ", dataSetName)

